In [1]:
import numpy as np

random_matrix = np.random.randint(1, 10, [6,4])
print(random_matrix)

[[4 8 6 7]
 [4 8 5 8]
 [3 6 8 3]
 [4 6 7 5]
 [9 9 8 4]
 [1 9 1 5]]


In [2]:
random_matrix[4:5] = np.add(random_matrix[0:1], random_matrix[2:3])
print(random_matrix)

[[ 4  8  6  7]
 [ 4  8  5  8]
 [ 3  6  8  3]
 [ 4  6  7  5]
 [ 7 14 14 10]
 [ 1  9  1  5]]


In [3]:
random_matrix[5:6] = np.add(random_matrix[1:2], random_matrix[3:4])
print(random_matrix)

[[ 4  8  6  7]
 [ 4  8  5  8]
 [ 3  6  8  3]
 [ 4  6  7  5]
 [ 7 14 14 10]
 [ 8 14 12 13]]
