## Exercises

<b>Remember that if you run into any problems, it's a good habit to refer to NumPy documentation.</b>

1. Create array with values [1, 0, 2, 4, 0, 0, 7], reverse it and find indices of zero-valued elements.

In [64]:
import numpy as np
arr = np.array([1,0,2,4,0,0,7])

#to reverse an array in numpy you can use flip() a bulit in function.
r_arr = np.flip(arr)
print("Rverse array : ",r_arr)


#to find indexes of number in an array you can use builting function np.where(arr == value you want to find index)
index_zeros =  np.where(r_arr == 0)
print("Indexes of zeros : ",index_zeros)



Rverse array :  [7 0 0 4 2 0 1]
Indexes of zeros :  (array([1, 2, 5], dtype=int64),)


2. Use previously created array, and find 3 highest and lowest values, and their indices.

In [76]:
r_arr2 = r_arr.copy()

###argsort sorts the array and provide the indexes of sorted array
indexes = np.argsort(r_arr2)
print(indexes)

max_indexs = indexes[-3:]
print("Highest values indexes: ", max_indexs)
print("Highest values : ", r_arr2[max_indexs] )


min_indexs = indexes[:3]
print("lowest values indexes: ", min_indexs)
print("lowest values : ", r_arr2[min_indexs] )





[1 2 5 6 4 3 0]
Highest values indexes:  [4 3 0]
Highest values :  [2 4 7]
lowest values indexes:  [1 2 5]
lowest values :  [0 0 0]


3. Create two random arrays and calculate euclidean distance between them.

In [80]:
a = np.random.randint(0,10,3)
b = np.random.randint(10,20,3)

print(a)
print(b)

# using linalg.norm()
dist = np.linalg.norm(a - b)

print(dist)

[5 6 9]
[10 16 13]
11.874342087037917


4. Try to obtain element-wise sum and element-wise multiplication of `x` and `y` using pure Python only.

In [88]:
%%timeit
add = []

l = len(a)
for i in range(l):
    add.append(a[i] + b[i])
    
# print(add)

mul = []

l = len(a)
for i in range(l):
    mul.append(a[i] * b[i])
    
# print(mul)


6.54 µs ± 631 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


5. Perform previous task using NumPy and compare the times of execution.

In [89]:
%%timeit
np.add(a,b)
np.multiply(a,b)


2.09 µs ± 163 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


6. Create two random arrays of size 3x4. To each of the arrays, add a row containing a maximum value in each column and then add a column containing a minimum value in each row. You should obtain two 4x5 matrices. Then concatenate them along last dimension. In the end add a row containing sum of values of each column and then add a column containing sum of values in each row.

7. Create function, that can calculate cartesian product between two arrays.